# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"A\n\x0fVerifyPartProto\x12\n\n\x02pk\x18\x01 \x01(\x0c\x12\x10\n\x08gamma_g2\x18\x02 \x01(\x0c\x12\x10\n\x08part_dec\x18\x03 \x01(\x0c\"y\n\x12\x44\x65\x63ryptParamsProto\x12\x0b\n\x03\x65nc\x18\x01 \x01(\x0c\x12\x0b\n\x03pks\x18\x02 \x03(\x0c\x12\r\n\x05parts\x18\x03 \x03(\x0c\x12\x0b\n\x03sa1\x18\x04 \x01(\x0c\x12\x0b\n\x03sa2\x18\x05 \x01(\x0c\x12\n\n\x02iv\x18\x06 \x01(\x0c\x12\t\n\x01t\x18\x07 \x01(\x04\x12\t\n\x01n\x18\x08 \x01(\x04\" \n\x0cGammaG2Proto\x12\x10\n\x08gamma_g2\x18\x01 \x01(\x0c\"\x1d\n\x0bResultProto\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFYPARTPROTO']._serialized_start=17
  _globals['_VERIFYPARTPROTO']._serialized_end=82
  _globals['_DECRYPTPARAMSPROTO']._serialized_start=84
  _globals['_DECRYPTPARAMSPROTO']._serialized_end=205
  _globals['_GAMMAG2PROTO']._serialized_start=207
  _globals['_GAMMAG2PROTO']._serialized_end=239
  _globals['_RESULTPROTO']._serialized_start=241
  _globals['_RESULTPROTO']._serialized_end=270
# @@protoc_insertion_point(module_scope)

class VerifyPartProto(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _globals['_VERIFYPARTPROTO']

class DecryptParamsProto(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _globals['_DECRYPTPARAMSPROTO']

class GammaG2Proto(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _globals['_GAMMAG2PROTO']

class ResultProto(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _globals['_RESULTPROTO']