name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up python
      run: |
        python3 -m venv tests/venv
        source tests/venv/bin/activate
        pip install -r tests/requirements.txt
        deactivate
    - name: Get transcript.json
      run: wget https://github.com/ethereum/kzg-ceremony/raw/main/transcript.json
    - name: Set up directories
      run: |
        mkdir tests/pks
        mkdir tests/sks
        mkdir tests/parts
    - name: Run tests
      run: |
        chmod +x run_test.sh
        ./run_test.sh
